name: Publish

on:
  release:
    types: [published]

jobs:
  ####### Publish to npm
  npm_publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610  # v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - name: npm publish
        env:
          IS_ALPHA: ${{ contains(github.ref, 'alpha')}}
          IS_BETA: ${{ contains(github.ref, 'beta')}}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ ${IS_ALPHA} = true ]; then export NPM_TAG="--tag alpha"; fi
          if [ ${IS_BETA} = true ]; then export NPM_TAG="--tag beta"; fi
          npm ci
          ([[ ! -f dist/index.cjs  ]] || [[ ! -f dist/index.js ]]) && exit 1
          npm publish ${NPM_TAG}
