name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm run test-sauce
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

  ####### Publish to npm
  npm_publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - name: npm publish
        env:
          IS_ALPHA: ${{ contains(github.ref, 'alpha')}}
          IS_BETA: ${{ contains(github.ref, 'beta')}}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ ${IS_ALPHA} = true ]; then export NPM_TAG="--tag alpha"; fi
          if [ ${IS_BETA} = true ]; then export NPM_TAG="--tag beta"; fi
          npm ci
          npm publish ${NPM_TAG}
